src/main/java/com/beyond/jellyorder/common/exception/CommonErrorDTO.java
src/main/java/com/beyond/jellyorder/common/exception/CommonExceptionHandler.java

- 공통응답에러DTO 및 공통예처리객체 수정
- postman테스트로 예외응답값을 받지 못해 확인한 결과 CommonErrorDTO에 getter메서드가 빠져있어 Json으로 변환하지 못했음
- CommonErrorDTO에 @Getter 추가
- 반환되는 에러 응답 객체는 JSON형식이기에 ControllerAdvice가 아닌 RestControllerAdvice로 바꿔줘야 됨.
-  CommonExceptionHandle에 @ControllerAdivce -> @RestControllerAdivce로 변환함.
- close #14 

Fix: 공통응답에러DTO 및 공통예처리객체 수정

---

src/main/java/com/beyond/jellyorder/common/BaseIdAndTimeEntity.java
src/main/java/com/beyond/jellyorder/common/BaseIdEntity.java

공통 UUID ID 엔티티(BaseIdEntity, BaseIdAndTimeEntity) 생성
<br/>
- Hibernate의 uuid2 전략을 활용하여 UUID를 자동 생성하는 공통 식별자 엔티티 BaseIdEntity 생성
- BaseTimeEntity를 상속하고 UUID 자동 생성 기능을 포함한 확장 엔티티 BaseIdAndTimeEntity 추
- 추후 모든 도메인 엔티티가 해당 공통 엔티티를 상속받아 일관된 ID 생성 및 생성/수정 시간 추적 기능을 공유할 수 있도록 구조화
- UUID 타입은 CHAR(36) 문자 기반으로 설정되어 있어 MariaDB 등 문자 기반 DB에 안전하게 저장 가능
- 코드 재사용성과 유지보수성을 높이기 위한 기반 설계 단계
<br/>
close #13 
<br/>
- Hibernate는 기본적으로 UUID를 BINARY(16) 형태로 저장하려 하기 때문에, 명시적으로 CHAR(36) 설정을 통해 문자 기반 UUID 저장을 유도함
- BaseTimeEntity가 미리 정의되어 있어 해당 상속 계층을 유지하며 통합 구조 확장
<br/>

[Feat] 공통 UUID ID 엔티티(BaseIdEntity, BaseIdAndTimeEntity) 생성 (#13)

---

src/main/java/com/beyond/jellyorder/common/BaseTimeEntity.java

BaseTimeEntity의 시간 처리 및 @Column 명시 방식 개선
<br/>
- ZoneId.of("Asia/Seoul") 중복 호출을 상수 ZONE_ID로 추출하여 코드 가독성과 유지보수성 향상
- @Column에 nullable = false를 명시하여 명확한 스키마 의도 전달
- 중복된 시간 설정 로직 제거로 간결성 확보
<br/>
close #21 
<br/>
- 해당 변경은 DB에 직접적인 DDL 영향을 주지 않지만, nullable = false는 마이그레이션 시 주의 필요
<br/>

[Refactor] BaseTimeEntity에 ZONE_ID 상수 분리 및 중복 제거 (#21)

---

src/main/java/com/beyond/jellyorder/common/s3/S3Uploader.java
src/main/java/com/beyond/jellyorder/domain/test/TestController.java

S3 업로드 파일명 중복 방지를 위한 UUID 적용 및 테스트 API 개선
<br/>
- S3 객체명 중복 방지를 위해 기존 파일명 뒤에 UUID를 추가
- uploadMenuImage()의 fileName 구성 방식 수정: 원래 파일명 + "-" + UUID
- /test/s3test API에서 MultipartFile과 이름(name)을 함께 받아 TestDTO 구성 후 업로드 가능하도록 변경
- 기존 테스트용 POST API (photo 단일 파라미터 방식) 제거
<br/>
close #23 
<br/>
- 반환된 S3 URL을 통해 실제 이미지 접근 가능 여부를 확인해 테스트 완료
- 추후 S3 삭제 로직 구현 시, 생성된 파일명의 UUID 처리 방식과 동일한 key 추출 필요
- 테스트 결과 (정상 수행 확인):
<br/>

[Feat] S3 업로드 로직 개선 및 테스트 API 정비 (#23)

---

src/main/java/com/beyond/jellyorder/common/exception/CommonExceptionHandler.java
src/main/java/com/beyond/jellyorder/domain/category/controller/CategoryController.java
src/main/java/com/beyond/jellyorder/domain/category/domain/Category.java
src/main/java/com/beyond/jellyorder/domain/category/dto/CategoryCreateReqDto.java
src/main/java/com/beyond/jellyorder/domain/category/dto/CategoryCreateResDto.java
src/main/java/com/beyond/jellyorder/domain/category/repository/CategoryRepository.java
src/main/java/com/beyond/jellyorder/domain/category/repository/CategoryRepositoryCustom.java
src/main/java/com/beyond/jellyorder/domain/category/repository/CategoryRepositoryCustomImpl.java
src/main/java/com/beyond/jellyorder/domain/category/service/CategoryService.java

- 본 PR은 카테고리 등록 기능 전반에 대한 구현을 포함하며, 도메인 설계부터 API 엔드포인트 구현까지 전체 계층 구조를 구성하고 연결하는 작업입니다. 클라이언트가 카테고리를 생성할 수 있도록 하기 위해 필요한 모든 구성 요소를 계층별로 구분하고 책임을 명확히 하여 구현하였습니다.
<br/>
- 우선 도메인 계층에서는 Category 엔티티를 정의하였습니다. 이는 매장 내 메뉴를 분류하는 단위로 사용되며, storeId, name, description 필드를 포함합니다. 현재 storeId는 인증 기반 매장 관리 기능 도입 전이므로 String 타입으로 임시 설정되어 있으며, 추후 UUID 타입으로의 전환이 예정되어 있습니다. 해당 엔티티는 BaseIdAndTimeEntity를 상속받아 생성일 및 수정일을 자동으로 관리할 수 있도록 하였습니다.
- DTO 계층에서는 카테고리 생성을 위한 요청 DTO인 CategoryCreateReqDto와 응답 DTO인 CategoryCreateResDto를 정의하였습니다. 요청 DTO에는 NotBlank 및 Size와 같은 유효성 검증 어노테이션을 적용하여, 입력 값에 대한 검증을 서버 단에서 선제적으로 수행할 수 있도록 하였습니다. 응답 DTO는 UUID, name, description 필드를 포함하며, 모든 필드를 final로 선언하여 불변 객체로 설계하였습니다. 이를 통해 응답 데이터의 무결성과 안정성을 확보하였습니다.
- Repository 계층에서는 JpaRepository를 상속하는 CategoryRepository를 정의하였으며, …

[Feat] 카테고리 추가 API 구현 (#33)

---

src/main/java/com/beyond/jellyorder/common/exception/CommonExceptionHandler.java
src/main/java/com/beyond/jellyorder/domain/ingredient/controller/IngredientController.java
src/main/java/com/beyond/jellyorder/domain/ingredient/domain/Ingredient.java
src/main/java/com/beyond/jellyorder/domain/ingredient/domain/IngredientStatus.java
src/main/java/com/beyond/jellyorder/domain/ingredient/dto/IngredientCreateReqDto.java
src/main/java/com/beyond/jellyorder/domain/ingredient/dto/IngredientCreateResDto.java
src/main/java/com/beyond/jellyorder/domain/ingredient/repository/IngredientRepository.java
src/main/java/com/beyond/jellyorder/domain/ingredient/repository/IngredientRepositoryCustom.java
src/main/java/com/beyond/jellyorder/domain/ingredient/repository/IngredientRepositoryCustomImpl.java
src/main/java/com/beyond/jellyorder/domain/ingredient/service/IngredientService.java

- 식자재(Ingredient) 등록 기능 전체 구현 – 엔티티, DTO, Repository, Service, Controller, 예외 처리 포함
<br/>
- Ingredient 엔티티 및 IngredientStatus Enum 정의: 매장에서 사용하는 식자재를 관리하기 위한 Ingredient 엔티티를 정의하였으며, 식자재의 재고 상태는 IngredientStatus Enum으로 관리한다. 기본 컬럼은 storeId, name, status이며, BaseIdAndTimeEntity를 상속받아 UUID 기반 식별자와 생성/수정 시간을 자동 관리하도록 구성하였다.
- 식자재 생성 요청 및 응답 DTO 정의: 클라이언트로부터 전달받는 요청은 IngredientCreateReqDto로, 응답은 IngredientCreateResDto로 분리하여 명확하게 설계하였다. 유효성 검증을 위해 @NotBlank, @NotNull, @Size 등의 애너테이션을 활용하였으며, 상태 값은 Enum 기반으로 제한하였다.
- Repository 인터페이스 및 중복 검사 기능 구현: IngredientRepository는 JpaRepository를 상속하여 기본 CRUD 기능을 제공하며, 추가로 existsByStoreIdAndName() 메서드를 통해 동일 매장 내 중복 이름 여부를 확인할 수 있도록 하였다. 확장 가능성을 고려하여 Custom Repository 인터페이스도 구성하였다.
- Service 레이어에서 비즈니스 로직 구현: IngredientService에서는 중복 이름 검사, 엔티티 생성 및 저장, 응답 …

[Feat] 식자재 추가 API 구현 (#35)

---

src/main/java/com/beyond/jellyorder/domain/store/entity/Store.java
src/main/java/com/beyond/jellyorder/domain/storetable/controller/StoreTableController.java
src/main/java/com/beyond/jellyorder/domain/storetable/dto/StoreTableDetail.java
src/main/java/com/beyond/jellyorder/domain/storetable/dto/StoreTableListResDTO.java
src/main/java/com/beyond/jellyorder/domain/storetable/entity/StoreTable.java
src/main/java/com/beyond/jellyorder/domain/storetable/repository/StoreTableRepository.java
src/main/java/com/beyond/jellyorder/domain/storetable/service/StoreTableService.java

전체 테이블 리스트 조회 api 구현
<br/>
- 각 매장의 구역별 전체 테이블 조회 API를 구현하였습니다.
- 응답 객체를 구역별 테이블 형식으로 정리했습니다.
<br/>
close #31
<br/>
- 현 로직은 N+1 문제가 발생되기에 추후 fetch join을 도입하려고 하려고 합니다.
- fetch join으로 인한 해결은 8.2일까지 완료 예정입니다.
<br/>

[Feat] 전체 테이블 리스트 조회 api 구현 (#31)

---

src/main/java/com/beyond/jellyorder/domain/category/controller/CategoryController.java
src/main/java/com/beyond/jellyorder/domain/category/dto/CategoryCreateReqDto.java
src/main/java/com/beyond/jellyorder/domain/category/dto/GetCategoryResDto.java
src/main/java/com/beyond/jellyorder/domain/category/repository/CategoryRepository.java
src/main/java/com/beyond/jellyorder/domain/category/service/CategoryService.java
src/main/java/com/beyond/jellyorder/domain/ingredient/repository/IngredientRepository.java
src/main/java/com/beyond/jellyorder/domain/menu/controller/MenuController.java
src/main/java/com/beyond/jellyorder/domain/menu/domain/Menu.java
src/main/java/com/beyond/jellyorder/domain/menu/domain/MenuIngredient.java
src/main/java/com/beyond/jellyorder/domain/menu/domain/MenuIngredientId.java
src/main/java/com/beyond/jellyorder/domain/menu/dto/MenuCreateReqDto.java
src/main/java/com/beyond/jellyorder/domain/menu/dto/MenuCreateResDto.java
src/main/java/com/beyond/jellyorder/domain/menu/repository/MenuIngredientRepository.java
src/main/java/com/beyond/jellyorder/domain/menu/repository/MenuRepository.java
src/main/java/com/beyond/jellyorder/domain/menu/repository/MenuRepositoryCustom.java
src/main/java/com/beyond/jellyorder/domain/menu/repository/MenuRepositoryCustomImpl.java
src/main/java/com/beyond/jellyorder/domain/menu/service/MenuService.java

카테고리 목록 조회 API 구현 (storeId 기준으로 필터링된 카테고리 리스트 반환)
<br/>
- CategoryService에 getCategoriesByStore(String storeId) 메서드 구현
- storeId 유효성 검사 (null, 공백, 존재 여부 확인)
- 존재하지 않을 경우 EntityNotFoundException 발생
- CategoryRepository에 findAllByStoreId(String storeId) 쿼리 메서드 추가
- CategoryController에 @GetMapping("/store/{storeId}") 엔드포인트 추가
- 인증/인가 미적용 상태이며 추후 SecurityContext에서 사용자 정보 추출 예정
- 현재는 테스트 목적상 URL 경로에서 storeId를 직접 받는 방식 유지
- 응답 DTO GetCategoryResDto 클래스 생성
- UUID id, String name 포함, @Getter, @AllArgsConstructor 적용
- Service → Controller → Client 데이터 전달 포맷 담당
- 전체적으로 코드 정리 및 주석 보강 (TODO 및 보안 관련 설명 포함)
<br/>
close #52 
<br/>
- 현재 storeId는 String 형태로 처리 중이며, 추후 UUID 타입으로 변경 예정
- 로그인 및 보안 기능이 구현되면, 인증된 사용자의 storeId를 기반으로 필터링 예정
<br/>

[Feat] 카테고리 불러오기 API 구현 (#52)

---

src/main/java/com/beyond/jellyorder/domain/category/controller/CategoryController.java
src/main/java/com/beyond/jellyorder/domain/category/repository/CategoryRepository.java
src/main/java/com/beyond/jellyorder/domain/category/service/CategoryService.java
src/main/java/com/beyond/jellyorder/domain/menu/repository/MenuRepository.java

카테고리 삭제 기능 구현 및 안정성 개선
<br/>
- MenuRepository에 existsByCategory_StoreIdAndCategory_Name 메서드 추가
- CategoryService 내 삭제 로직 개선: 메뉴 존재 여부 확인 및 JPQL 기반 삭제 처리
- CategoryRepository에 @Modifying JPQL 삭제 쿼리 메서드 deleteByStoreIdAndName 추가
- CategoryController에 카테고리 삭제용 DELETE API 엔드포인트 추가
- EntityManager 제거 및 의존성 정리
<br/>
close #61 
<br/>
- storeId는 현재 String 타입으로 유지되며, 추후 UUID로 전환 예정
- StaleObjectStateException 방지를 위해 JPQL 삭제 쿼리 사용
<br/>

[Feat] 카테고리 삭제 API 구현 (#61)

---

src/main/java/com/beyond/jellyorder/domain/menu/controller/MenuController.java
src/main/java/com/beyond/jellyorder/domain/menu/repository/MenuRepository.java
src/main/java/com/beyond/jellyorder/domain/menu/service/MenuService.java

storeId와 메뉴명을 기반으로 한 단일/다중 메뉴 조회 API 기능 구현
<br/>
이번 작업에서는 매장의 고유 식별자인 storeId를 기준으로 단일 메뉴와 전체 메뉴를 각각 조회할 수 있는 기능을 구현하였습니다. 먼저 MenuRepository에 카테고리 연관 관계를 활용한 파생 쿼리 메서드인 findByCategory_StoreIdAndName과 findAllByCategory_StoreId를 추가하여, 메뉴 이름 기반 단건 조회와 매장 전체 메뉴 리스트 조회가 가능하도록 하였습니다.
이후 MenuService에서는 해당 쿼리 메서드를 호출하는 getMenuByStoreIdAndName과 getMenusByStoreId 메서드를 구현하여 각각 메뉴 한 건 또는 전체를 조회하고, 이를 DTO(MenuCreateResDto)로 매핑하여 반환하도록 구성했습니다. 예외 상황에 대한 처리를 명확히 하기 위해 메뉴가 존재하지 않을 경우에는 EntityNotFoundException을 발생시킵니다.
마지막으로 MenuController에는 RESTful한 API 설계 원칙에 따라 GET 요청으로 각각의 조회를 처리하는 두 개의 엔드포인트를 추가하였습니다. /menu/store/{storeId}/name/{menuName} 경로는 단일 메뉴 조회를, /menu/store/{storeId} 경로는 전체 메뉴 목록 조회를 담당합니다. 단건 조회 메시지는 사용자 입장에서 의미가 명확하도록 "단일 메뉴 조회가 정상적으로 조회되었습니다."로 수정하였습니다.
<br/>
close #64 
<br/>
- 현재는 …

[Feat] 단일 메뉴 조회/메뉴 목록 조회 API 구현 (#64)

---

src/main/java/com/beyond/jellyorder/domain/menu/controller/MenuController.java
src/main/java/com/beyond/jellyorder/domain/menu/domain/Menu.java
src/main/java/com/beyond/jellyorder/domain/menu/dto/MenuCreateReqDto.java
src/main/java/com/beyond/jellyorder/domain/menu/dto/MenuCreateResDto.java
src/main/java/com/beyond/jellyorder/domain/menu/service/MenuService.java
src/main/java/com/beyond/jellyorder/domain/option/dto/OptionAddReqDto.java
src/main/java/com/beyond/jellyorder/domain/option/dto/OptionAddResDto.java
src/main/java/com/beyond/jellyorder/domain/option/mainOption/domain/MainOption.java
src/main/java/com/beyond/jellyorder/domain/option/mainOption/dto/MainOptionDto.java
src/main/java/com/beyond/jellyorder/domain/option/subOption/domain/SubOption.java
src/main/java/com/beyond/jellyorder/domain/option/subOption/dto/SubOptionDto.java

메뉴 옵션 추가 로직을 개선하여, 기존에는 메인 옵션명 중복만 검증하던 방식에서 메인 옵션명 + 서브 옵션명 조합 중복 검증이 가능하도록 변경하였습니다. 이로 인해 동일한 메인 옵션 내에서도 새로운 서브 옵션을 추가할 수 있으며, 요청 본문 내부의 중복 서브 옵션 입력도 방지됩니다. 또한 OptionAddResDto에 서브 옵션 생성 개수(addedSubOptionCount) 필드를 추가하여 응답 정보의 활용성을 높였습니다.
<br/>
- MenuService.addOptionsToMenu 로직 변경
- 기존의 메인 옵션명 단독 중복 검증 → 메인 옵션명 + 서브 옵션명 조합 중복 검증으로 변경
- 동일 메인 옵션이 존재할 경우, 해당 메인 옵션 하위에 새로운 서브 옵션을 추가 가능하도록 수정
- 요청 본문 내부에서 동일한 서브 옵션명이 반복되는 경우 예외 발생 처리
- OptionAddResDto에 addedSubOptionCount 필드 추가
- 추가된 서브 옵션 개수를 응답에 포함시켜 클라이언트에서 통계 및 후처리에 활용 가능
- 중복 검증 로직 강화 및 데이터 무결성 보장
<br/>
close #78 
<br/>
- 기존 API 스펙에는 변화가 없으나, 응답 DTO 구조(OptionAddResDto)에 필드가 추가되었으므로 해당 응답을 사용하는 클라이언트 측 로직 수정이 필요할 수 있습니다.
- 추후 메뉴 수정 API 구현 시, 동일한 방식의 컬렉션 동기화 로직을 적용하여 ID 유지한 상태로 옵션 수정이 가능하도록 할 예정입니다.
<br/>

[Feat] 메뉴 옵션 추가 API 구현 (#78)

---

src/main/java/com/beyond/jellyorder/domain/ingredient/controller/IngredientController.java
src/main/java/com/beyond/jellyorder/domain/ingredient/dto/IngredientListResDto.java
src/main/java/com/beyond/jellyorder/domain/ingredient/dto/IngredientResDto.java
src/main/java/com/beyond/jellyorder/domain/ingredient/repository/IngredientRepository.java
src/main/java/com/beyond/jellyorder/domain/ingredient/service/IngredientService.java

storeId를 기반으로 해당 매장이 등록한 모든 식자재(Ingredient) 목록을 조회하는 API를 구현하였습니다.
<br/>
- IngredientRepository에 findAllByStoreId(String storeId) 메서드 추가하여 매장별 식자재 조회 기능 구현
- IngredientService에 getIngredientsByStoreId 메서드 추가
- 추후 storeRepository.existsById를 활용해 storeId 유효성 검증 가능하도록 구조 설계
- 조회 결과가 없는 경우 예외를 발생시키지 않고 빈 리스트를 담아 반환
- Ingredient 엔티티를 IngredientResDto 리스트로 변환 후 IngredientListResDto에 담아 응답
- IngredientController에 GET /{storeId}/ingredients 엔드포인트 추가
- 서비스 메서드 호출 후 조회된 결과를 ApiResponse 포맷으로 반환
- 조회 성공 시 "원재료 목록이 정상적으로 조회되었습니다." 메시지와 함께 결과 전송
<br/>
close #88 
<br/>
- 현재 storeId 유효성 검증 로직은 주석 처리 상태이며, 추후 Store 테이블과의 연관관계 설정 완료 시 활성화 예정
- 조회 결과가 없더라도 빈 리스트를 반환하므로, 프론트엔드에서 null 처리 없이 그대로 데이터 렌더링 가능
<br/>

[Feat] 식자재 불러오기 API 구현 (#88)

---

src/main/java/com/beyond/jellyorder/domain/ingredient/controller/IngredientController.java
src/main/java/com/beyond/jellyorder/domain/ingredient/domain/Ingredient.java
src/main/java/com/beyond/jellyorder/domain/ingredient/dto/IngredientDeleteReqDto.java
src/main/java/com/beyond/jellyorder/domain/ingredient/dto/IngredientDeleteResDto.java
src/main/java/com/beyond/jellyorder/domain/ingredient/dto/IngredientDto.java
src/main/java/com/beyond/jellyorder/domain/ingredient/repository/IngredientRepository.java
src/main/java/com/beyond/jellyorder/domain/ingredient/service/IngredientService.java
src/main/java/com/beyond/jellyorder/domain/menu/controller/MenuController.java
src/main/java/com/beyond/jellyorder/domain/menu/domain/Menu.java
src/main/java/com/beyond/jellyorder/domain/menu/domain/MenuIngredient.java
src/main/java/com/beyond/jellyorder/domain/menu/domain/MenuIngredientId.java
src/main/java/com/beyond/jellyorder/domain/menu/dto/MenuListResDto.java
src/main/java/com/beyond/jellyorder/domain/menu/service/MenuService.java

메뉴와 식자재 간 연관 매핑 구조를 개선하고, 식자재 삭제 API를 구현했습니다. 또한 메뉴 목록 조회 시 식자재 정보를 함께 반환하도록 DTO를 변경했습니다.
<br/>
- MenuIngredientId에 equals/hashCode를 구현하고, MenuIngredient에 EmbeddedId 및 @MapsId를 적용해 복합키 매핑 안정성을 확보했습니다.
- Ingredient와 Menu 엔티티에 OneToMany(cascade = ALL, orphanRemoval = true)를 적용해 연관 엔티티 삭제 시 일관된 처리 가능하도록 수정했습니다.
- 식자재 삭제 요청/응답 DTO(IngredientDeleteReqDto, IngredientDeleteResDto)를 추가하고, 영향 메뉴를 조회하는 네이티브 쿼리 메서드를 IngredientRepository에 구현했습니다.
- 메뉴 조회 응답 DTO를 MenuListResDto로 교체하여 ingredients 필드 포함, 컨트롤러의 반환 타입을 변경했습니다.
- MenuService#create 로직 순서를 조정해 메뉴 저장 후 옵션/식자재를 매핑하도록 수정했습니다.
<br/>
close #90 
<br/>
<br/>

[Feat] 식자재 삭제 API 구현 (#90)

---

src/main/java/com/beyond/jellyorder/domain/order/controller/OrderStatusController.java
src/main/java/com/beyond/jellyorder/domain/order/dto/orderStatus/OrderStatusMenu.java
src/main/java/com/beyond/jellyorder/domain/order/dto/orderStatus/OrderStatusMenuOption.java
src/main/java/com/beyond/jellyorder/domain/order/dto/orderStatus/OrderStatusResDTO.java
src/main/java/com/beyond/jellyorder/domain/order/entity/UnitOrder.java
src/main/java/com/beyond/jellyorder/domain/order/repository/UnitOrderRepository.java
src/main/java/com/beyond/jellyorder/domain/order/service/OrderStatusService.java
src/main/java/com/beyond/jellyorder/domain/store/entity/Store.java
src/main/java/com/beyond/jellyorder/domain/store/service/StoreService.java
src/main/java/com/beyond/jellyorder/domain/storetable/dto/orderTableStatus/MenuDetail.java

주문 현황 리스트 조회 API 구현
<br/>
-  store테이블에 매장 개시(business_opened_at), 마감 시간(business_closed_at) 컬럼를 추가하였습니다.
추후 매장 개시 및 마감 기능을 위해 추가하였습니다.
각 매장별로 매장 오픈 이후 발생되는 주문건을 조회할 조건이 필요하기 때문에 추가하였습니다.
- 주문 상태값에 따라 unitOrder(단건주문)을 조회하는 로직을 구현했습니다.
1. 엔드포인트에 각 주문 상태값을 입력하여 조회할 수 있습니다. (ACCEPT, COMPLETE, CANCEL)
2. 페이지네이션을 적용하여 전체데이터가 아닌 20개의 주문들만 가져왔습니다.
<br/>
close #115 
<br/>
N+1문제가 발생되기 때문에 추후 프로젝션 혹은 배치사이즈조절을 도입할 예정입니다.
<br/>

[Feat] 주문 현황 리스트 조회 API 구현 (#115)

---

src/main/java/com/beyond/jellyorder/common/exception/CommonExceptionHandler.java
src/main/java/com/beyond/jellyorder/domain/order/controller/OrderStatusController.java
src/main/java/com/beyond/jellyorder/domain/order/dto/orderStatus/OrderStatusMenu.java
src/main/java/com/beyond/jellyorder/domain/order/dto/orderStatus/OrderStatusMenuOption.java
src/main/java/com/beyond/jellyorder/domain/order/dto/orderStatus/OrderStatusResDTO.java
src/main/java/com/beyond/jellyorder/domain/order/dto/orderStatus/OrderStatusUpdateReqDTO.java
src/main/java/com/beyond/jellyorder/domain/order/dto/orderStatus/UnitOrderStatusResDTO.java
src/main/java/com/beyond/jellyorder/domain/order/entity/UnitOrder.java
src/main/java/com/beyond/jellyorder/domain/order/repository/UnitOrderRepository.java
src/main/java/com/beyond/jellyorder/domain/order/service/OrderStatusService.java
src/main/java/com/beyond/jellyorder/domain/store/entity/Store.java
src/main/java/com/beyond/jellyorder/domain/store/service/StoreService.java
src/main/java/com/beyond/jellyorder/domain/storetable/dto/orderTableStatus/MenuDetail.java

주문 상태 값 변경 API 구현
<br/>
- 현재 접수된 주문들을 '조리완료', '주문취소' 가 가능하도록 상태를 변경하는 로직을 구성했습니다.
- Patch메서드를 통한 수정 요청이며, 엔드포엔트에 UnitOrder의 id값을 url에 포함 및 http body부분에 원하는 status값을 요청합니다.
- 주문 취소의 경우 주문했던 메뉴의 하루판매량을 다시 감소하는 로직을 구현했습니다.
- 테스트 예시 (조리완료)
- 테스트 예시 (주문취소)
- 취소된 재고 하루판매량 감소
<br/>
close #117 
<br/>
- 주문 취소 시 동시성 이슈가 발생할 수 있기 때문에 추후 redis도입이 필요해 보입니다.
<br/>

[Feat] 주문 상태 값 변경 API 구현 (#117)

---

src/main/java/com/beyond/jellyorder/domain/menu/controller/MenuController.java
src/main/java/com/beyond/jellyorder/domain/menu/dto/MenuUpdateReqDto.java
src/main/java/com/beyond/jellyorder/domain/menu/service/MenuService.java

메뉴 수정 기능 구현 (DTO 정의, Service 로직, Controller API 추가)
<br/>
- MenuUpdateReqDto 추가
- 카테고리명, 메뉴명, 가격, 설명, 원산지, 판매 제한 등 필드 정의
- 이미지 파일(MultipartFile) 및 메인/서브 옵션 트리 포함
- NotBlank, Size, Min 등 유효성 검증 어노테이션 적용
- Service update 로직 구현
- 매장 소속 검증 및 메뉴 소속 일치 여부 확인
- 카테고리 변경 처리 및 스칼라 필드(name/price/description/origin/salesLimit) 갱신
- onSale 정책(수동 품절/해제 토글) 반영 및 재고 상태 자동 재계산
- 이미지 교체(S3 업로드 후 기존 삭제) 로직 추가
- 옵션 트리(MainOption/SubOption) 및 식자재 동기화 로직 구현
- Controller API 추가
- PutMapping("/update"), consumes = MULTIPART_FORM_DATA 적용
- ModelAttribute Valid MenuUpdateReqDto 바인딩 및 검증
- PreAuthorize("hasRole('STORE')") 보안 적용
- 수정 성공 시 MenuAdminResDto 반환
<br/>
close #111 
<br/>
- 옵션 트리 및 식자재 동기화는 이름 기반 diff 방식으로 동작하므로, 클라이언트에서 중복/빈 이름 전송 시 예외 발생 가능
- 이미지 교체는 S3 업로드 성공 후 기존 이미지 삭제하도록 구현되어 있음
<br/>
PR이 다음 요구 사항을 …

[Feat] 메뉴 수정 기능 구현 (#111)

---

src/main/java/com/beyond/jellyorder/domain/ingredient/service/IngredientService.java
src/main/java/com/beyond/jellyorder/domain/menu/repository/MenuIngredientRepository.java

식자재 삭제 시 메뉴 상태 복원 로직 추가
<br/>
- 삭제된 식자재로 인해 OUT_OF_STOCK 되었던 메뉴가 판매제한 소진이 아니고 남아있는 식자재가 모두 EXHAUSTED가 아닐 경우 ON_SALE로 복구
- MenuIngredientRepository에 `countExhaustedByMenuId` 쿼리 추가하여 메뉴별 남은 소진 상태 식자재 개수 확인 가능
- IngredientService.delete 로직 내 메뉴 상태 재평가 및 상태 복원 처리 추가
<br/>
close #139 
<br/>
- SOLD_OUT_MANUAL 상태의 메뉴는 복원 로직에서 제외됨
- 판매제한(salesLimit) 소진 상태인 경우에는 상태 OUT_OF_STOCK 상태 유지
<br/>

[Fix] 식자재 삭제 시 메뉴 상태 복원 로직 추가 (#139)

---

src/main/java/com/beyond/jellyorder/domain/menu/dto/MenuCreateReqDto.java
src/main/java/com/beyond/jellyorder/domain/menu/dto/MenuUpdateReqDto.java
src/main/java/com/beyond/jellyorder/domain/menu/repository/MenuRepository.java
src/main/java/com/beyond/jellyorder/domain/menu/service/MenuService.java

메뉴 수정/생성 흐름 확장: 새 카테고리 설명 지원 + 식자재 ID 기반 연동 + MenuService 로직 보강
<br/>
- **DTO 확장**
- `MenuCreateReqDto`에 `categoryDescription` 추가(선택, 최대 255자) — 새 카테고리 생성 시 설명 입력 지원
- `MenuUpdateReqDto`에 `categoryDescription`, `ingredientIds` 추가 — 수정 시 카테고리 설명 반영 및 식자재 ID 기반 연동 가능
- **Service 로직 보강 (`MenuService`)**
- 새 카테고리 생성 시 `categoryDescription`까지 저장되도록 처리
- 카테고리 변경 시 존재하지 않으면 생성 후 메뉴에 할당
- 식자재 연동을 **이름 기반 → ID 기반**으로 전환: `syncIngredientsByIds(menu, requestedIds, storeUuid)`
- 존재하지 않는 식자재/타 매장 소속 식자재에 대한 예외 처리 강화
- **기타**
- 불필요한 중복 로직 정리 및 NPE 방지용 방어 코드 추가
<br/>
close #141 
<br/>
- `categoryDescription`은 **새 카테고리 생성 시에만** 의미가 있으며, 기존 카테고리 선택 시 무시됩니다.
- 식자재 연동은 이제 **ID 기준**으로만 동작하므로, 프론트엔드에서 `ingredientIds` 전달이 보장되어야 합니다.
<br/>

[Feat, Fix] 새 카테고리 설명 지원 + 식자재 ID 기반 연동 + MenuService 로직 보강 (#141)

---

src/main/java/com/beyond/jellyorder/domain/order/entity/TotalOrder.java
src/main/java/com/beyond/jellyorder/domain/order/service/OrderStatusService.java

주문 취소 시 TotalOrder의 가격 변경 로직 추가
<br/>
- 기존 로직은 추문을 취소하더도 totalOrder의 가격이 변하지 않았습니다.
- 주문 취소하게 되면 해당 UnitOrder의 속해있는 모든 가격을 계산하여 TotalOrder의 가격을 감소시켰습니다.
<br/>
close #145 
<br/>
<br/>

[Chore] 주문 취소 시 TotalOrder의 가격 변경 로직 추가 (#145)

---

src/main/java/com/beyond/jellyorder/domain/menu/dto/MenuCreateReqDto.java
src/main/java/com/beyond/jellyorder/domain/menu/service/MenuService.java

<br/>
- MenuService.create 리팩터
- 식자재: ID 기반 연동(ingredientIds)으로 동기화, 타 매장 식자재 차단
- 재고: 수동품절이 아닌 경우 식자재 상태로 재계산(소진 → OUT_OF_STOCK, 그 외 ON_SALE).
<br/>
close #169 
<br/>
<br/>

Feat: 메뉴 생성 로직/DTO 리팩터 — ingredientIds(UUID) 도입 (#169)

---

src/main/java/com/beyond/jellyorder/domain/order/entity/TotalOrder.java
src/main/java/com/beyond/jellyorder/domain/sales/controller/SalesController.java
src/main/java/com/beyond/jellyorder/domain/sales/dto/CounterPaymentReqDTO.java
src/main/java/com/beyond/jellyorder/domain/sales/entity/Sales.java
src/main/java/com/beyond/jellyorder/domain/sales/entity/SalesStatus.java
src/main/java/com/beyond/jellyorder/domain/sales/service/SalesService.java
src/main/java/com/beyond/jellyorder/domain/storetable/dto/orderTableStatus/OrderMenuDetailPrice.java
src/main/java/com/beyond/jellyorder/domain/storetable/service/OrderTableStatusService.java

카운터 결제 API 수정
<br/>
- 카운터 결제 시 현금, 카드 결제 처리 api 구현했습니다.
- 해당 total_order에 대한 CARD, CASH 중 선택하여 결제 처리했습니다.
- 결제 처리 시 서비스로직에서 sales엔티티 생성 및 저장, store_table의 상태값을 'STANBY'로 변경, total_order의 endedAt와paymentedAt 시간 업데이트하였습니다.
- 활성상태인 주문이 있을 시 롤백처리했습니다.
<br/>
close #176 
<br/>
<br/>

[Refactor] 카운터 결제 API 수정 (#176)

---

src/main/java/com/beyond/jellyorder/domain/order/entity/TotalOrder.java
src/main/java/com/beyond/jellyorder/domain/order/repository/OrderMenuRepository.java
src/main/java/com/beyond/jellyorder/domain/order/service/OrderStatusService.java
src/main/java/com/beyond/jellyorder/domain/storetable/controller/OrderTableStatusController.java
src/main/java/com/beyond/jellyorder/domain/storetable/dto/orderTableStatus/OrderTableUpdateReqDTO.java
src/main/java/com/beyond/jellyorder/domain/storetable/service/OrderTableStatusService.java

주문테이블 수정 API 리팩토링
<br/>
- 기존 List형식의 요청에서 단건 주문(UnitOrder)로 변경
- TotalOrder의 totalCount필드값을 최신화 하는 내부 메서드 정의
- OrderMenu리포지토리에 취소된 단건주문을 제외한 나머지 OrderMenu리스트를 fetchJoin하는 로직 추가 
<br/>
close #181 
<br/>
<br/>

[Refactor] 주문테이블 수정 API 리팩토링 (#181)

---

src/main/java/com/beyond/jellyorder/common/redis/DefaultRedisConfig.java
src/main/java/com/beyond/jellyorder/common/redis/OrderNumberRedisConfig.java
src/main/java/com/beyond/jellyorder/domain/order/service/CollectOrderNumberService.java
src/main/java/com/beyond/jellyorder/domain/order/service/UnitOrderService.java
src/main/java/com/beyond/jellyorder/domain/test/TestController.java

Redis로 주문번호 생성 로직 구현
<br/>
- redis의 4번 DB에 order:seq:storeId 키값으로 채번테이블 구현
- 주문 시 redisTemplate에서 채번하여 unitOrder 생성할 때 insert
- 마감 시 주문번호 초기화를 위해 키값을 삭제할 수 있는 resetOrderNum메서드 구현 
<br/>
close: #193 
<br/>
- 마감 백엔드 로직 때 주문번호 초기화를 위한 메서드입니다.
<br/>

[Feat] Redis로 주문번호 생성 로직 구현 (#193)
